// This file is generated by scripts/01_fetch_affordability_data.js. Do not edit manually.

export type TimeSeriesDataPoint = {
  readonly year: number;
  readonly value: number;
};

export type CountryData = {
  readonly pti: readonly TimeSeriesDataPoint[];
  readonly ptr: readonly TimeSeriesDataPoint[];
  readonly mortgageRate: readonly TimeSeriesDataPoint[];
  readonly income: readonly TimeSeriesDataPoint[];
  readonly rent: readonly TimeSeriesDataPoint[];
};

export type AffordabilityData = {
  readonly [countryCode: string]: CountryData;
};

export const affordabilityData = {
  "CAN": {
    "pti": [
      {
        "year": 1985,
        "value": 4.5
      },
      {
        "year": 1990,
        "value": 5.2
      },
      {
        "year": 1995,
        "value": 4.8
      },
      {
        "year": 2000,
        "value": 5
      },
      {
        "year": 2005,
        "value": 6.5
      },
      {
        "year": 2010,
        "value": 7.8
      },
      {
        "year": 2015,
        "value": 9
      },
      {
        "year": 2020,
        "value": 11.2
      },
      {
        "year": 2025,
        "value": 12.5
      }
    ],
    "ptr": [
      {
        "year": 1985,
        "value": 18
      },
      {
        "year": 1990,
        "value": 22
      },
      {
        "year": 1995,
        "value": 20
      },
      {
        "year": 2000,
        "value": 21
      },
      {
        "year": 2005,
        "value": 25
      },
      {
        "year": 2010,
        "value": 30
      },
      {
        "year": 2015,
        "value": 35
      },
      {
        "year": 2020,
        "value": 42
      },
      {
        "year": 2025,
        "value": 45
      }
    ],
    "mortgageRate": [
      {
        "year": 1985,
        "value": 12.5
      },
      {
        "year": 1990,
        "value": 13
      },
      {
        "year": 1995,
        "value": 8.5
      },
      {
        "year": 2000,
        "value": 7
      },
      {
        "year": 2005,
        "value": 5.2
      },
      {
        "year": 2010,
        "value": 3.8
      },
      {
        "year": 2015,
        "value": 2.9
      },
      {
        "year": 2020,
        "value": 2.1
      },
      {
        "year": 2025,
        "value": 5.5
      }
    ],
    "income": [
      {
        "year": 1985,
        "value": 35000
      },
      {
        "year": 1990,
        "value": 42000
      },
      {
        "year": 1995,
        "value": 45000
      },
      {
        "year": 2000,
        "value": 50000
      },
      {
        "year": 2005,
        "value": 58000
      },
      {
        "year": 2010,
        "value": 65000
      },
      {
        "year": 2015,
        "value": 72000
      },
      {
        "year": 2020,
        "value": 80000
      },
      {
        "year": 2025,
        "value": 88000
      }
    ],
    "rent": [
      {
        "year": 1985,
        "value": 500
      },
      {
        "year": 1990,
        "value": 650
      },
      {
        "year": 1995,
        "value": 700
      },
      {
        "year": 2000,
        "value": 800
      },
      {
        "year": 2005,
        "value": 950
      },
      {
        "year": 2010,
        "value": 1100
      },
      {
        "year": 2015,
        "value": 1250
      },
      {
        "year": 2020,
        "value": 1500
      },
      {
        "year": 2025,
        "value": 1800
      }
    ]
  },
  "USA": {
    "pti": [
      {
        "year": 1985,
        "value": 3.8
      },
      {
        "year": 1990,
        "value": 4.1
      },
      {
        "year": 1995,
        "value": 4
      },
      {
        "year": 2000,
        "value": 4.5
      },
      {
        "year": 2005,
        "value": 5.8
      },
      {
        "year": 2010,
        "value": 4.7
      },
      {
        "year": 2015,
        "value": 5.1
      },
      {
        "year": 2020,
        "value": 6.2
      },
      {
        "year": 2025,
        "value": 7
      }
    ],
    "ptr": [
      {
        "year": 1985,
        "value": 16
      },
      {
        "year": 1990,
        "value": 18
      },
      {
        "year": 1995,
        "value": 17
      },
      {
        "year": 2000,
        "value": 19
      },
      {
        "year": 2005,
        "value": 24
      },
      {
        "year": 2010,
        "value": 20
      },
      {
        "year": 2015,
        "value": 22
      },
      {
        "year": 2020,
        "value": 28
      },
      {
        "year": 2025,
        "value": 32
      }
    ],
    "mortgageRate": [
      {
        "year": 1985,
        "value": 11.5
      },
      {
        "year": 1990,
        "value": 10.1
      },
      {
        "year": 1995,
        "value": 7.9
      },
      {
        "year": 2000,
        "value": 8.1
      },
      {
        "year": 2005,
        "value": 5.9
      },
      {
        "year": 2010,
        "value": 4.7
      },
      {
        "year": 2015,
        "value": 3.9
      },
      {
        "year": 2020,
        "value": 2.9
      },
      {
        "year": 2025,
        "value": 6.8
      }
    ],
    "income": [
      {
        "year": 1985,
        "value": 38000
      },
      {
        "year": 1990,
        "value": 45000
      },
      {
        "year": 1995,
        "value": 48000
      },
      {
        "year": 2000,
        "value": 55000
      },
      {
        "year": 2005,
        "value": 62000
      },
      {
        "year": 2010,
        "value": 68000
      },
      {
        "year": 2015,
        "value": 75000
      },
      {
        "year": 2020,
        "value": 85000
      },
      {
        "year": 2025,
        "value": 95000
      }
    ],
    "rent": [
      {
        "year": 1985,
        "value": 450
      },
      {
        "year": 1990,
        "value": 600
      },
      {
        "year": 1995,
        "value": 650
      },
      {
        "year": 2000,
        "value": 750
      },
      {
        "year": 2005,
        "value": 900
      },
      {
        "year": 2010,
        "value": 1050
      },
      {
        "year": 2015,
        "value": 1200
      },
      {
        "year": 2020,
        "value": 1450
      },
      {
        "year": 2025,
        "value": 1750
      }
    ]
  }
} as const;
